apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-prod
  namespace: {{ .Values.spec.destination.namespace}}
spec:
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: app-sub
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    namespace: prod
    name: kubernetes-admin@kubernetes
  syncPolicy:
    automated:
      prune: true

