apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-test
  namespace: {{ .Values.spec.destination.namespace}}
spec:
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: app-sub
    helm:
      valueFiles:
        - values.yaml
        - values-test.yaml
  destination:
    namespace: test
    name: {{ .Values.spec.destination.name }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=orphan