apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prometheus
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: offline
            name: in-cluster
          - cluster: online
            name: online
  template:
    metadata:
      name: 'prometheus-{{cluster}}'
    spec:
      project: default
      source:
        repoURL: git@github.com:saihide/argocd-example-apps.git
        targetRevision: master
        path: prometheus/{{cluster}}
      destination:
        name: '{{name}}'
        namespace: monitoring